import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

const theme = createTheme({
  direction: "rtl",
  palette: {
    mode: "light",
    background: {
      default: "#f5f5f5",
      // main page background
    },
    primary: {
      main: "#4CAF50",
      // buttons color
    },
  },
  typography: {
    fontFamily: "Tahoma, Arial",
  },
});
