import { Geist, Geist_Mono } from "next/font/google";
import { Lalezar } from "next/font/google";
import "./globals.css";

const lalezar = Lalezar({
  weight: "400",
  subsets: ["arabic"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
{
  /* // ${geistSans.variable} ${geistMono.variable} */
}
{
  /* // {`${lalezar.variable} `} */
}
